-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#0f1416",
	base01 = "#0f1416",
	base02 = "#171c1f",
	base03 = "#40484c",
	base04 = "#bfc8cc",
	base05 = "#dee3e6",
	base06 = "#2c3134",
	base07 = "#343a3c",
	base08 = "#ffb4ab",
	base09 = "#c2c3eb",
	base0A = "#b3cad4",
	base0B = "#87d1eb",
	base0C = "#424465",
	base0D = "#004e60",
	base0E = "#344a52",
	base0F = "#93000a",
})

local function transparent()
	local groups = {
		"Normal",
		"NormalNC",
		"SignColumn",
		"FoldColumn",
		"LineNr",
		"CursorLineNr",
		"EndOfBuffer",
		"MsgArea",
		"ModeMsg",
		"NormalFloat",
		"FloatBorder",
		"Pmenu",
		"PmenuSel",
		"PmenuSbar",
		"PmenuThumb",
		"WinSeparator",
		"StatusLine",
		"StatusLineNC",
		"TabLine",
		"TabLineFill",
		"TabLineSel",
	}

	for _, g in ipairs(groups) do
		vim.api.nvim_set_hl(0, g, { bg = "NONE" })
	end
end

transparent()
-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#004e60",
	fg = "#0f1416",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#e0e0ff",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#c2c3eb",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#b3cad4",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#04677e",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#0a0f11",
	fg = "#87d1eb",
})

local function hl(group, spec)
	vim.api.nvim_set_hl(0, group, spec)
end

hl("NeoTreeNormal", {
	bg = "#0a0f11",
	fg = "#dee3e6",
})

hl("NeoTreeNormalNC", {
	bg = "#0a0f11",
	fg = "#dee3e6",
})

hl("NeoTreeEndOfBuffer", {
	bg = "#0a0f11",
	fg = "#0a0f11",
})

hl("NeoTreeCursorLine", {
	bg = "#171c1f",
})

hl("NeoTreeWinSeparator", {
	fg = "#40484c",
	bg = "#0a0f11",
})

hl("NeoTreeDirectoryName", { fg = "#87d1eb" })
hl("NeoTreeDirectoryIcon", { fg = "#87d1eb" })

hl("NeoTreeFileName", { fg = "#dee3e6" })
hl("NeoTreeFileNameOpened", {
	fg = "#b3cad4",
	italic = true,
})

hl("NeoTreeRootName", {
	fg = "#c2c3eb",
	bold = true,
})

hl("NeoTreeIndentMarker", { fg = "#40484c" })
hl("NeoTreeExpander", { fg = "#40484c" })

set_hl_mutliple({ "NeoTreeGitAdded", "NeoTreeGitUntracked" }, {
	fg = "#87d1eb",
})

set_hl_mutliple({ "NeoTreeGitModified", "NeoTreeGitConflict" }, {
	fg = "#c2c3eb",
})

set_hl_mutliple({ "NeoTreeGitDeleted", "NeoTreeGitIgnored" }, {
	fg = "#ffb4ab",
})

hl("NeoTreeFloatNormal", {
	bg = "#0a0f11",
	fg = "#dee3e6",
})

hl("NeoTreeFloatBorder", {
	bg = "#0a0f11",
	fg = "#40484c",
})

hl("NeoTreeTitleBar", {
	bg = "#004e60",
	fg = "#e0e0ff",
})
