-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "{{colors.background.default.hex}}",
	base01 = "{{colors.background.default.hex}}",
	base02 = "{{colors.surface_container_low.default.hex}}",
	base03 = "{{colors.outline_variant.default.hex}}",
	base04 = "{{colors.on_surface_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.inverse_on_surface.default.hex}}",
	base07 = "{{colors.surface_bright.default.hex}}",
	base08 = "{{colors.error.default.hex}}",
	base09 = "{{colors.tertiary.default.hex}}",
	base0A = "{{colors.secondary.default.hex}}",
	base0B = "{{colors.primary.default.hex}}",
	base0C = "{{colors.tertiary_container.default.hex}}",
	base0D = "{{colors.primary_container.default.hex}}",
	base0E = "{{colors.secondary_container.default.hex}}",
	base0F = "{{colors.error_container.default.hex}}",
})

local function transparent()
	local groups = {
		"Normal",
		"NormalNC",
		"SignColumn",
		"FoldColumn",
		"LineNr",
		"CursorLineNr",
		"EndOfBuffer",
		"MsgArea",
		"ModeMsg",
		"NormalFloat",
		"FloatBorder",
		"Pmenu",
		"PmenuSel",
		"PmenuSbar",
		"PmenuThumb",
		"WinSeparator",
		"StatusLine",
		"StatusLineNC",
		"TabLine",
		"TabLineFill",
		"TabLineSel",
	}

	for _, g in ipairs(groups) do
		vim.api.nvim_set_hl(0, g, { bg = "NONE" })
	end
end

transparent()
-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{colors.primary_container.default.hex}}",
	fg = "{{colors.background.default.hex}}",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "{{colors.on_tertiary_container.default.hex}}",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "{{colors.secondary.default.hex}}",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "{{colors.inverse_primary.default.hex}}",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.primary.default.hex}}",
})

local function hl(group, spec)
	vim.api.nvim_set_hl(0, group, spec)
end

hl("NeoTreeNormal", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
})

hl("NeoTreeNormalNC", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
})

hl("NeoTreeEndOfBuffer", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.surface_container_lowest.default.hex}}",
})

hl("NeoTreeCursorLine", {
	bg = "{{colors.surface_container_low.default.hex}}",
})

hl("NeoTreeWinSeparator", {
	fg = "{{colors.outline_variant.default.hex}}",
	bg = "{{colors.surface_container_lowest.default.hex}}",
})

hl("NeoTreeDirectoryName", { fg = "{{colors.primary.default.hex}}" })
hl("NeoTreeDirectoryIcon", { fg = "{{colors.primary.default.hex}}" })

hl("NeoTreeFileName", { fg = "{{colors.on_surface.default.hex}}" })
hl("NeoTreeFileNameOpened", {
	fg = "{{colors.secondary.default.hex}}",
	italic = true,
})

hl("NeoTreeRootName", {
	fg = "{{colors.tertiary.default.hex}}",
	bold = true,
})

hl("NeoTreeIndentMarker", { fg = "{{colors.outline_variant.default.hex}}" })
hl("NeoTreeExpander", { fg = "{{colors.outline_variant.default.hex}}" })

set_hl_mutliple({ "NeoTreeGitAdded", "NeoTreeGitUntracked" }, {
	fg = "{{colors.primary.default.hex}}",
})

set_hl_mutliple({ "NeoTreeGitModified", "NeoTreeGitConflict" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

set_hl_mutliple({ "NeoTreeGitDeleted", "NeoTreeGitIgnored" }, {
	fg = "{{colors.error.default.hex}}",
})

hl("NeoTreeFloatNormal", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
})

hl("NeoTreeFloatBorder", {
	bg = "{{colors.surface_container_lowest.default.hex}}",
	fg = "{{colors.outline_variant.default.hex}}",
})

hl("NeoTreeTitleBar", {
	bg = "{{colors.primary_container.default.hex}}",
	fg = "{{colors.on_tertiary_container.default.hex}}",
})
